### ISSUE TITLE
Problem including console in post

### ISSUE THREAD

**Issue by lyonsa** [silshack/spring2014#200]
So I completed the exercises and was trying to include all my code in a console in the post. But it didn't really work. 

Here's a link to what it looks like: http://lyonsa.github.io/spring2014/2014/01/30/allenliststring.html

and here's the raw: https://raw.github.com/lyonsa/spring2014/gh-pages/_posts/2014-01-30-allenliststring.md

**Comment by lyonsa** [comment]
@eah13 
@gerbal

**Comment by gerbal** [comment]
@lyonsa Because of the way the code console works (It looks for an html element id, of which only one in the whole page can be valid), it only works one time in the whole post.

For now, just replace the console with code blocks. I'm looking into getting the console working in this situation, but it might be a few weeks until I have a good solution.
